apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  suspend: false
  dependsOn:
    - name: kured
    - name: ingress-nginx
    - name: my-secrets
  interval: 5m
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenants/mixed-arch-k3s
  prune: true
  validation: client
---
apiVersion: v1
kind: Namespace
metadata:
  name: okteto
