---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: okteto-flux
  namespace: okteto
spec:
  chart:
    spec:
      chart: flux
      sourceRef:
        kind: HelmRepository
        name: okteto-apps
      version: 1.10.0
  interval: 30m0s
  releaseName: okteto-flux
  targetNamespace: fluxcd

