kind: Secret
apiVersion: v1
metadata:
    labels:
        dev.okteto.com: "true"
    name: okteto-regcred
    namespace: fluxcd
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:5aY4lj8ZgHaRMOyL5nGXBYhtXKCu4Vx35PIvoiK0/ewuyNu/Z+S5gYH9cPl65CrMsh6dDYu1CZsxuJJPUfAYotuBcKP+JE7WgkBysdIIBXRErKvr1/vyVGep6f5zHEs1OBcARCAgNrXM764WW1jrIzIAg3xxJG0UyXIOXzsq15hWCvHK8g8/DJfgxvUoDPWj63zmJ3J1BK1XV1BNhYoNDqCx6JEWWDXXj15njA==,iv:jw7PoWHxTLMoC8PNEZXspq843/Q16a/l4vmlGnkgdWY=,tag:XdAtoRiAQGwkP0uijF0E/Q==,type:str]
    okteto-token: ENC[AES256_GCM,data:TGHxFI9Oe3bCLYEdIl5hOVSxenmi8lUN6xRVnNDCH2luXU/+WE2jxEvaMlKsLr7RS1/ll8w3zig=,iv:7xH9oLIpq5WkM/5YST0LBxfZgylyaFjrToH8iuMplUg=,tag:wBbKSiXJ7yYICzkDIjLn6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-18T04:06:41Z"
    mac: ENC[AES256_GCM,data:RebsF54QzpRB0hvZzQ8dXzmrmUdlijChqAsLp7X6ej5n7NNCrI2nwK+gJPhQxvfz7Wi0tfFR5+MEXio2ZoH6zbQR8glmzUK/PpsLW9FFeyuOEtIwvyltj8dhMBt5LWfFebZ3/83sNRJDICeOL3EzLTqoxwrd/tjZJU5y1jQHBO4=,iv:Yo/PVcOLDxObngMrW1O2oYCp1HZ4gii6+2y1+FeBbrk=,tag:1bTrp8A+XYXha42x5h5eTg==,type:str]
    pgp:
        - created_at: "2021-07-18T04:06:40Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8KWpFFEpDMeAQ//UXNZX5y3I/QfDPQTV62GhElvx6uTut6PWZsqb3ARQljw
            dJjPboBX0+aCFCSXiBa5Vva581wOMuZsqqsGSAl0SCItRkbgxA5sgvmBc6jJ0xGV
            xs/LwvxyFjY2xc/hIKvZ8lf4P2QaxTmGPvmuU35oda8Ql4VIIbDVXtv3CTgh6oWJ
            MpgcnXhRuKtcYNkQnWUitkhTSdQ1PutZAZBZ8TCiHIOht8vzxJSa5UwijCh/WoXG
            bn5ADt7cEMQsVPchMPig67wjbDP1lrKB0P64ED275cbZjj6wjcBpxKfbkzD2nkIV
            BLCSlDhkUTIeTCJI6mS/RvO9q0Fc2alkiJojf04HysIlrzTUqfh1RgA2zXacxQVw
            gXgH3pWugPwdNNvb0ztogpRZesn1aToV2ckTkSwbhDnfP0apXSkKAQyWVTAKKJ/V
            xY9I3/Z+Okaf2hhYMJoz3J8ymtup7DRruGEAqJMSvcXfrgaY9MU1dup/AeKot3kg
            oS2JSqKc/irteyQ4zh0C+8KNU6lnyPuFewd4lYK5ECLaPAGzC8Eouug1WTBW+9Cl
            2nK849fWyClfT7Unny9yiK8wNVTE1p5jtl59CM6NdYQuQ04yB/ziTOtwECI1Uj6N
            buX1eR6/etDgbFqQ+oEglnBxuPa9Qe1GgyjJoeq6uPmwYN1z9Yir9p9STXVjKOTU
            ZgEJAhUrc3DONDSvJRWNdrSaLix/dFkSvqSmFcuqvEmfbbLibwVsqJC7w4QYRjtu
            O+895qtep6s5XXqGZewTsyeIKp84vDUvG53Nj8/XVIl4/z73xjQavNOHf8qQaIUx
            4bWrT6hfJg==
            =iFQ3
            -----END PGP MESSAGE-----
          fp: 3BC6DB4B252D44B3DF71C0C577D51558632FE260
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
